version: "3.6"

services:
  ws_db:
    image: postgres:11
    container_name: ws_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    networks:
      - ws_network
    ports:
      - 5432:5432
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_inil.sql
    

  ws_engine:
    container_name: ws_engine
    build:
      context: ./ws-engine/
      dockerfile: ./Dockerfile
    environment:
      - DELAY_BETWEEN_QUERIES=1000
      - PROC_COUNT=1
      - ASYNCWORKERS_COUNT=1
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - POSTGRES_SERVER=ws_db
      - POSTGRES_PORT=5432
    depends_on:
      - ws_db
    networks:
      - ws_network
      
  ws_backend:
    container_name: ws_backend
    build:
      context: ./ws-backend/
      dockerfile: ./Dockerfile    
    environment:
      - DATABASE_URI=${DATABASE_URI}
    ports:
      - 5000:5000
    depends_on:
      - ws_db
    networks:
      - ws_network
#    volumes:
#      - ${WS_ENGINE}:/opt/ws_engine



networks:
  ws_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}
        
